OLED_ENABLE = yes
OLED_DRIVER = SSD1306

CONSOLE_ENABLE = yes
EXTRAKEY_ENABLE = yes
WPM_ENABLE = yes 
LTO_ENABLE = yes
NKRO_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE  = no

TAP_DANCE_ENABLE = yes
MOUSEKEY_ENABLE = yes
